### ISSUE TITLE
Add to melpa?

### ISSUE THREAD

**Issue by catesandrew** [spion/purscheck#4]

**Comment by spion** [comment]
I don't think its good enough to publish at the moment. There are some troubles which make purscheck unsuitable for regular use. 

I need to update it first for 0.7 as well as switch it to use `psc-make` instead of `psc` for performance (right now it recompiles the entire project every time, whereas afterwards it will only recompile changed units)

**Comment by spion** [comment]
Closing as this has been superseded by far better tools.
